SFGoogleIntegration-main/GoogleSheetIntegratiom/force-app/main/default/objects/google_sheet__c/google_sheet__c.object-meta.xml
<CustomObject>
    <label>google sheet</label>
    <nameField>
        <label>google Sheet ext Id Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>google sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFGoogleIntegration-main/GoogleSheetIntegratiom/force-app/main/default/objects/google_sheet__c/fields/Dev_Name__c.field-meta.xml
<CustomField>
    <fullName>Dev_Name__c</fullName>
    <label>Dev Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SFGoogleIntegration-main/GoogleSheetIntegratiom/force-app/main/default/objects/google_sheet__c/fields/google_Sheet_ext_Id__c.field-meta.xml
<CustomField>
    <fullName>google_Sheet_ext_Id__c</fullName>
    <label>google Sheet ext Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SFGoogleIntegration-main/GoogleSheetIntegratiom/force-app/main/default/objects/google_sheet__c/fields/Google_url__c.field-meta.xml
<CustomField>
    <fullName>Google_url__c</fullName>
    <label>Google url</label>
    <type>Url</type>
</CustomField>

SFGoogleIntegration-main/GoogleSheetIntegratiom/force-app/main/default/classes/sampleclassTestClass.cls
@isTest
private class sampleclassTestClass {
    @istest static void TestGetselectOptions(){
        list<string> fieldslist =new list<string>();
        fieldslist.add('Id');
        fieldslist.add('LastName');
        fieldslist.add('FirstName');
        
        google_sheet__c gSheet = new google_sheet__c();
        gSheet.Name = 'Contact';
		gSheet.Dev_Name__c = 'SalesforceToSmartdataOnsiteAccount';
        gSheet.Google_url__c = 'https://docs.google.com/spreadsheets/d/1acRexpF9t88TqIBUzvuf1kpPbu7on5od7uwLT9HsoFQ/edit';
        gSheet.google_Sheet_ext_Id__c = '1acRexpF9t88TqIBUzvuf1kpPbu7on5od7uwLT9HsoFQ';
        insert gSheet;
        
        String devName = gSheet.Dev_Name__c;
        
        Test.startTest();
        test.setMock(HttpCalloutMock.class , new sampleclassMockClass());
        sampleclass.getCredentials();
        sampleclass.sample(devName);
        sampleclass.getdata('Contact', devName);
		Test.stopTest();
    }  

}